name: Build binaries

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest] 
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - run: git fetch --prune --unshallow

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      # - name: Install dependencies (macos)
      #   if: matrix.os == 'macos-latest'
      #   run: |
      #     brew install wxwidgets@3.0
      #     ln -s /usr/local/bin/wx-config-3.0 /usr/local/bin/wx-config

      - name: Build binaries
        run: make
      
      - uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with: 
          name: stm32flash-bin-win
          path: ./stm32flash.exe
      - uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-latest'
        with: 
          name: stm32flash-bin-macos
          path: ./stm32flash
      - uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        with: 
          name: stm32flash-bin-linux
          path: ./stm32flash
