name: Build binaries

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest] 
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - run: git fetch --prune --unshallow

      # - name: Install dependencies (ubuntu)
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install wx3.0-headers libwxgtk3.0-gtk3-0v5 libwxgtk3.0-gtk3-dev

      # - name: Install dependencies (macos)
      #   if: matrix.os == 'macos-latest'
      #   run: |
      #     brew install wxwidgets@3.0
      #     ln -s /usr/local/bin/wx-config-3.0 /usr/local/bin/wx-config

      - name: Build binaries
        run: make
      
      - uses: actions/upload-artifact@v3
        with: 
          name: stm32flash-bin
          path: bin/
